---
version: "3"
services:
 devopsdb:
   image: bhanuchandarsalkam/myrepo:dbimage
   ports:
     - "3306:3306"

 application:
   image: bhanuchandarsalkam/myrepo:appimage
   ports:
     - "1155:8080"
   depends_on:
     - "devopsdb"
