---
version: "3"
services:
 devopsdb:
   image: shaikmustafa/myrepo:dbimage
   ports:
     - "3306:3306"

 application:
   image: shaikmustafa/myrepo:appimage
   ports:
     - "1111:8080"
   depends_on:
     - "devopsdb"
